### ISSUE TITLE
Catch SIGINT (CTRL-C)

### ISSUE THREAD

**Issue by AmirHosein-Gharaati** [reza00farjam/rjdl#3]
When downloading a file, after quitting the program using CTRL+C, I get some errors of python :

![image](https://user-images.githubusercontent.com/56169125/89552566-90052c80-d821-11ea-9925-5ea9a554b968.png)

It would be nice to catch this signal and print something else like "Quitting..." and then remove the file.

This [link ](https://www.devdungeon.com/content/python-catch-sigint-ctrl-c) shall be helpful to create this feature.

**Comment by reza00farjam** [comment]
actually this is not an issue!
as you can see in the last line of the image, an error has raised as **ConnectionError: Connection Has Broken!**, i raised an error instead of a massage, cause this package is used in both scripts and console and in scripts it's better to have a raised error instead of a shown text error.

**Comment by reza00farjam** [comment]
added in new version 0.1.1, tnx for reporting.
